DROP TABLE IF EXISTS posts CASCADE;
DROP TABLE IF EXISTS  platforms CASCADE;
DROP TABLE IF EXISTS  post_platforms CASCADE;
DROP TABLE IF EXISTS  project_platforms CASCADE;
DROP TABLE IF EXISTS  comments CASCADE;